# Site settings
title: "Dżemi"
email: dzemikq@gmail.com
description: "Blog Dżemika"
baseurl: ""
url: "https://dzem.tk/"
title_description: "Siema! Mam na imię Jerry a tu będą się pojawiać moje blogi."
title_image: "https://i.imgur.com/q9T8UmC.gif"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://github.com/Dzemi/dzemi.github.io
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: Dzemi42
github_username:  Dzemi
reddit_username: 
linkedin_link: https://dzem.tk/
stackoverflow_link: https://dzem.tk/

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
